### ISSUE TITLE
Unable to connect to the setup AP

### ISSUE THREAD

**Issue by softwarecrash** [daromer2/InverterOfThings#2]
Hello,
yeah this is the project what i need, thanks.
i would bring the data to my smart home from a chinese solar inverter (i sun easun ...)
actualy the mqtt working?
can i help something? testing etc?
the founding/sponsor link/function are dead

i have set it up, but when i connect to the wifi ap the esp reset and i lost the connection, what can i do?

can you provide a list with used librays

**Comment by daromer2** [comment]
Im a tad late to reply here and havent gotten the notification. 
The Softap resets after like 30 seconds. A nicea feature *couch* bug*cough* :D

I can see you did your own now so a bit late to respond to the help part i guess. I will keep mine going for now since i dont need much functions extra. Though the code could be rewritten since its mostly copy paste. of course i have redone alot from the original since it didnt work

**Comment by softwarecrash** [comment]
no problem, so eventual we can make a thing from both sources and ideas?

**Comment by daromer2** [comment]
Btw you seem to have done some nice effort on yours! Forgot to add that. Ajax and all that is nice.

**Comment by softwarecrash** [comment]
thanks, hard work, im not a pro in this. so when you interested to fusion all this to a nice thing ;)
